name: kriptografi_idea
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  gallery_saver: ^2.3.2
  get: 4.6.1
  ionicons: ^0.1.2
  path_provider: ^2.0.9
  qr_code_scanner: ^0.7.0
  qr_flutter: ^4.0.0
  share_plus: ^3.1.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  lints: 1.0.1

flutter:
  fonts:
    - family: PatrickHand
      fonts:
        - asset: assets/fonts/PatrickHand.ttf
  uses-material-design: true

  assets:
    - assets/images/
